### ISSUE TITLE
Streaming version

### ISSUE THREAD

**Issue by mlomb** [fabiospampinato/base128-encoding#1]
Hi, I have to encode large binary buffers and found out that using base128 give me the best results in terms of disk space (UTF-8).
However, I can't just send the whole buffer because Chrome crashes (out of memory), so I have to stream the buffer in chunks. Concatenating `Buffer128.encode(chunk)` does not work so I was thinking if you see possible a streamed version of the encoder/decoder.

**Comment by fabiospampinato** [comment]
Legitimate use case but I'm not particularly interested in implementing this. I might consider a PR though, I'm not sure how much code would be needed to implement this and how portable it would be.

**Comment by fabiospampinato** [comment]
Closing as I'm not interested in adding streaming support.
